<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Design Patterns Example" />
    <meta name="author" content="Piotr Miazga" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <title>Design Patterns - <?php echo htmlentities($this->patternName); ?></title>
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="style.css" />
</head>
<body>
<div class="container">
    <div class="header">
        <ul class="nav nav-pills pull-right">
            <li class="active"><a href="index.php">Home</a></li>
        </ul>
        <h2 class="text-muted">Design Patterns</h2>
    </div>

    <div class="jumbotron">
        <h2><?php echo htmlentities($this->pageName); ?></h2>
        <p>
            <?php echo htmlentities($this->pageDescription); ?>
        </p>
    </div>
    <div>
        <?php echo $this->content; ?>
    </div>
    <div class="footer">
        Piotr Miazga
    </div>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>
